### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by asimaranov** [Sigtran/CC_GW_Parser#2]
I'm getting packet like this:
![dumppng](https://user-images.githubusercontent.com/25568730/34769444-e58ef304-f60e-11e7-8402-09d8049d022a.PNG)
Guildmember's names are filled.
And a can't get data from it. Result is 'not found' for each member

**Comment by Sigtran** [comment]
Try this..
'Save the capture as plain text (Wireshark --> File --> Export Packet Dissections --> As Plain Text)'

**Comment by asimaranov** [comment]
It didn't help. 
It look like this in notepad++
![image](https://user-images.githubusercontent.com/25568730/34773335-5d9ee798-f61c-11e7-85b9-5175a6363c10.png)
It should be?

**Comment by Sigtran** [comment]
nope. it should not. you should see it as plain text. tho i see you have unicode (Russian) names.. maybe that messes up the whole thing. attach a sample pcap if you want (full pcap, no plain text please), ill have a look later.
You can talk to me on line if you want. Add Sigtran

**Comment by asimaranov** [comment]
I updated my wireshark, and it started to work. But is there way to get scores from raw data?

**Comment by Sigtran** [comment]
what do you mean by raw data? pcap is the raw data, i just did it in a very lazy way to suit my needs. data extraction can be done in many different ways of course.
